In [1]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
a.dtype

dtype('int64')

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
a = np.array([
    [1,2],
    [3,4],
])

# Matrix like operations


In [22]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [26]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [40]:
a = np.random.rand(3,3)
b = np.random.rand(3,2)

In [41]:
a.dot(b)

array([[0.87692923, 1.21405489],
       [0.92237395, 1.05484957],
       [1.41661796, 1.6508132 ]])

In [47]:
np.round(a, 2)

array([[0.8 , 0.2 , 0.61],
       [0.82, 0.26, 0.17],
       [0.47, 0.98, 0.89]])

In [49]:
np.array([[1,2,3]]).transpose()

array([[1],
       [2],
       [3]])